### ISSUE TITLE
konveyor.io/lib-ui URL stopped working

### ISSUE THREAD

**Issue by mturley** [migtools/lib-ui#56]
The default GitHub Pages deployment for this repo is used for the Storybook component previews. It was originally accessible at konveyor.github.io/lib-ui, which now redirects to konveyor.io/lib-ui. That was working for a while but now is a 404.

@fdupont-redhat do you know what the deal is there, or who would know about the konveyor.io DNS stuff?

**Comment by fdupont-redhat** [comment]
See with @jameslabocki who changed the konveyor.io website hostname some weeks ago. Seems it broke this integration.

**Comment by mturley** [comment]
Will do, thanks Fabien.
